INSERT INTO OFFICE(ID, NAME, ADDRESS_ID, DEPARTMENT_ID) VALUES (1, 'Office of S&M Boston', 4, 1);
INSERT INTO OFFICE(ID, NAME, ADDRESS_ID, DEPARTMENT_ID) VALUES (2, 'Office of S&M New York', 5, 1);
INSERT INTO OFFICE(ID, NAME, ADDRESS_ID, DEPARTMENT_ID) VALUES (3, 'Office of R&D Boston', 6, 2);
INSERT INTO OFFICE(ID, NAME, ADDRESS_ID, DEPARTMENT_ID) VALUES (4, 'Office of A Los Angeles', 7, 3);