CREATE TABLE PERMISSION (
   ID  BIGSERIAL NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS PERMISSION ADD CONSTRAINT PERMISSION_NAME UNIQUE (NAME);

CREATE TABLE ROLE (
   ID  BIGSERIAL NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS ROLE ADD CONSTRAINT ROLE_NAME UNIQUE (NAME);

CREATE TABLE ROLES_PERMISSIONS (
   ROLE_ID INT8 NOT NULL,
   PERMISSION_ID INT8 NOT NULL,
   PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

ALTER TABLE IF EXISTS ROLES_PERMISSIONS ADD CONSTRAINT ROLES_PERMISSIONS_PERMISSION
  FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION;

ALTER TABLE IF EXISTS ROLES_PERMISSIONS ADD CONSTRAINT ROLES_PERMISSIONS_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE;

CREATE TABLE USER_ (
   ID  BIGSERIAL NOT NULL,
   ACCOUNT_EXPIRED BOOLEAN,
   ACCOUNT_LOCKED BOOLEAN,
   CREDENTIALS_EXPIRED BOOLEAN,
   ENABLED BOOLEAN,
   PASSWORD VARCHAR(255),
   USER_NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS USER_ ADD CONSTRAINT USER_USER_NAME UNIQUE (USER_NAME);

CREATE TABLE USERS_ROLES (
   USER_ID INT8 NOT NULL,
   ROLE_ID INT8 NOT NULL,
   PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE IF EXISTS USERS_ROLES ADD CONSTRAINT USERS_ROLES_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE;

ALTER TABLE IF EXISTS USERS_ROLES ADD CONSTRAINT USERS_ROLES_USER_
  FOREIGN KEY (USER_ID) REFERENCES USER_;
