INSERT INTO PERMISSION(ID, NAME) VALUES (1, 'COMPANY_CREATE');
INSERT INTO PERMISSION(ID, NAME) VALUES (2, 'COMPANY_READ');
INSERT INTO PERMISSION(ID, NAME) VALUES (3, 'COMPANY_UPDATE');
INSERT INTO PERMISSION(ID, NAME) VALUES (4, 'COMPANY_DELETE');

INSERT INTO PERMISSION(ID, NAME) VALUES (5, 'DEPARTMENT_CREATE');
INSERT INTO PERMISSION(ID, NAME) VALUES (6, 'DEPARTMENT_READ');
INSERT INTO PERMISSION(ID, NAME) VALUES (7, 'DEPARTMENT_UPDATE');
INSERT INTO PERMISSION(ID, NAME) VALUES (8, 'DEPARTMENT_DELETE');