INSERT INTO ROLE(ID, NAME) VALUES (1, 'COMPANY_ADMIN');
INSERT INTO ROLE(ID, NAME) VALUES (2, 'COMPANY_READER');
INSERT INTO ROLE(ID, NAME) VALUES (3, 'COMPANY_MODIFIER');

INSERT INTO ROLE(ID, NAME) VALUES (4, 'DEPARTMENT_ADMIN');
INSERT INTO ROLE(ID, NAME) VALUES (5, 'DEPARTMENT_READER');
INSERT INTO ROLE(ID, NAME) VALUES (6, 'DEPARTMENT_MODIFIER');

-- COMPANY
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (1, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (1, 3);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (1, 4);

INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (2, 2);

INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (3, 1);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (3, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (3, 3);

-- DEPARTMENT
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (4, 5);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (4, 6);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (4, 7);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (4, 8);

INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (5, 6);

INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (6, 5);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (6, 6);
INSERT INTO ROLES_PERMISSIONS(ROLE_ID, PERMISSION_ID) VALUES (6, 7);