CREATE TABLE ADDRESS
(
  ID BIGINT NOT NULL,
  HOUSE_NUMBER CHARACTER VARYING(255),
  STREET CHARACTER VARYING(255),
  ZIP_CODE CHARACTER VARYING(255),
  CONSTRAINT ADDRESS_PKEY PRIMARY KEY (ID)
)
WITH (
  OIDS=FALSE
);