CREATE TABLE COMPANY
(
  ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(255) NOT NULL,
  CONSTRAINT COMPANY_PKEY PRIMARY KEY (ID),
  CONSTRAINT UKS7T58YCLDRJRFTPUN092TKHU7 UNIQUE (NAME)
)
WITH (
  OIDS=FALSE
);